### ISSUE TITLE
the representation of the data for the Autonomous Province of Trento and the Autonomous Province of Bolzano are wrong

### ISSUE THREAD

**Issue by napo** [italia/covid19-dashboard-vaccini#31]
I suppose the problem is related to the topojson used because this contains the geometry of the region Trentino-Alto Adige/Sudtirol.
By starting from the shapefiles of ISTAT (regions and provinces) I created a new topojson with all the italian regions without the Trentino-Alto Adige / Sudtirol and, in substitution, the two geometries of the autonomous provinces.
The file is in attachment in this message.

I suppose that  replacing the file in public/data/geo/it.json with this and changing the variables in utils.js like so:
PAB: "Autonomous Province of Bolzano",
PAT: "Autonomous Province of Trento",
you can fix the problem.
I don't  have enough time to a test.

note:
the autonomous provinces of Trento and Bolzano manage  the health care independently from the Region, for this reason the data cannot be presented in an aggregate way.

[regioni_e_province_autonome.zip](https://github.com/italia/covid19-dashboard-vaccini/files/5772471/regioni_e_province_autonome.zip)

**Comment by sebbalex** [comment]
Hi @napo and thanks for the issue. You have perfectly identified the problem! We will try to apply the patch you suggest or we would be even happier if you submit a PR.

Anyway, thanks for your time. :+1:

**Comment by napo** [comment]
Thanks @libremente for the answer and the invitation to send you a PR.

Before to write code I suggest you to solve the [issue](https://github.com/italia/covid19-opendata-vaccini/issues/1) opened by @aborruso on the repository with the data.
The suggestion is to use the common id keys of ISTAT and Eurostat to join the tables to the geographical entities.

IMHO:  it's better if you use the NUTS2 code, so you can  have an elegant and coherent solution to solve the problem of the rappresentation for the two autonomous provinces.

Today the [@ondata](https://github.com/ondata) team published also the [geojson](https://github.com/ondata/nuts/blob/main/processing/NUTS2_g.geojson) ready to be used (more or less it's like the file that I attached on my previous comment)

**Comment by bfabio** [comment]
Hello @napo, the official dashboard is at https://github.com/italia/report-vaccini-anti-covid-19 (https://www.governo.it/it/cscovid19/report-vaccini/). It should be fixed there.

We're considering this repo as a quick example dashboard.
