### ISSUE TITLE
Fix horizontal scroll on mobile and other small other small fixes

### ISSUE THREAD

**Issue by melchionnaeu** [italia/covid19-dashboard-vaccini#38]
All mobile device have an horizontal scroll, certainly due to the width of the Italian map. See the screenshot below.

There are other small issues definitely to be fixed:

- [ ] Translate `Search:` on tables.
- [ ] Translate ` Show xy entries` on tables.
- [ ] Fix icon on mobile web app installation.
- [ ] Fix name of the web app for mobile, now is `React App`.

![IMG_2469](https://user-images.githubusercontent.com/37714897/103713253-28affc00-4fbc-11eb-973c-38c65650f91b.PNG)

**Comment by libremente** [comment]
> All mobile device have an horizontal scroll, certainly due to the width of the Italian map. See the screenshot below.
> 
> There are other small issues definitely to be fixed:
> 
>     * [ ]  Translate `Search:` on tables.
> 
>     * [ ]  Translate ` Show xy entries` on tables.
> 
>     * [ ]  Fix icon on mobile web app installation.
> 
>     * [ ]  Fix name of the web app for mobile, now is `React App`.
> 
> 
> ![IMG_2469](https://user-images.githubusercontent.com/37714897/103713253-28affc00-4fbc-11eb-973c-38c65650f91b.PNG)

Thanks @melchionnaeu for your complete report!
Confirming this and assigning the bug label.
We're definitely going to work on these issue soon and we'll let you know.
Any PR is appreciated :wink:

**Comment by bfabio** [comment]
Hello @melchionnaeu, this is just an example dashboard now, the official one is at https://github.com/italia/report-vaccini-anti-covid-19 (https://www.governo.it/it/cscovid19/report-vaccini/).

Anyway, it looks like those issues are fixed in the official one.

**Comment by melchionnaeu** [comment]
Perfect @bfabio 🤙
