### ISSUE TITLE
Separate the data between booster shot and first one

### ISSUE THREAD

**Issue by Francexi** [italia/covid19-dashboard-vaccini#56]
When booster shot (richiami) will be started, their number should be held separately from the first shot count. Something like this

|First shots|Booster shots|Total doses received|%|
|-------------|-----------------|-------------------------|---|
|9000|1000|20000|50%|

(in this example 20000 doses has beeen received in total, of which 9000 has been used as first shots, 1000 has been used as booster shots. 50% is based on the sum of first and booster shots)

**Comment by bfabio** [comment]
Hello @Francexi, this is just an example dashboard, the official one is at https://github.com/italia/report-vaccini-anti-covid-19 (https://www.governo.it/it/cscovid19/report-vaccini/).

**Comment by bfabio** [comment]
Closing (https://github.com/italia/report-vaccini-anti-covid-19/issues/2)
